import {rctf} from '../../rctf.mjs'
import {} from './mappings.js'

function transformKeysToRegExp(variable){
    return Object.keys(variable).filter(key => key !== '')
}

const labeledElementTypes = ['button', 'link', 'field', 'section break', 'checkbox', 'toggle button', 'icon', 'dropdown', 'radio', 'textarea']
window.parameterTypes = {
    tableTypes: transformKeysToRegExp(window.tableMappings),
    baseElement: transformKeysToRegExp(window.elementChoices),
    toDoTableTypes: transformKeysToRegExp(window.toDoListTables),
    userRightsChecks: transformKeysToRegExp(window.userRightChecks),
    ordinal: transformKeysToRegExp(window.ordinalChoices),
    recordStatusIcons: transformKeysToRegExp(window.recordStatusIcons),
    fileRepoIcons: transformKeysToRegExp(window.fileRepoIcons),
    participantListIcons: transformKeysToRegExp(window.participantListIcons),
    action: ['click on', 'check', 'uncheck', 'should see', 'should NOT see'],
    addEditField: ['Add New Field', 'Edit Field'],
    addField: ['Add Field', 'Add Matrix of Fields', 'Import from Field Bank'],
    addOrSelect: ['add', 'select'],
    articleType: ['a', 'an', 'the'],
    aboveBelow: ['above', 'below'],
    beforeAfter: ['before', 'after'],
    cellAction: [
        ' and click the new instance link',
        ' and click on the bubble',
        ' and click the repeating instrument bubble for the first instance',
        ' and click the repeating instrument bubble for the second instance',
        ' and click the repeating instrument bubble for the third instance',
    ],
    check: ['checked', 'unchecked', 'in the enabled state', 'in the disabled state'],
    checkBoxRadio: ['checkbox', 'radio', 'toggle button'],
    clickType: ['click on', 'check', 'uncheck', 'enable', 'disable'],
    columnLabel: ['', 'in the Matrix column'],
    confirmation: ['accept', 'cancel'],
    dateTimeType: ['timestamp', 'date', 'datetime'],
    dataViewingRights: ['No Access', 'Read Only', 'View & Edit', 'Edit survey responses'],
    dropdownType: ['dropdown', 'multiselect', 'checkboxes', 'radio'],
    editEvent: ['Edit', 'Delete'],
    editField: ['Edit', 'Edit Matrix', 'Branching Logic', 'Copy', 'Move', 'Delete Field'],
    editSurveyRights: [
        ' with Edit survey responses checked',
        ' with Edit survey responses unchecked',
    ],
    elementStatus: ['that is disabled', 'that is checked', 'that is unchecked'],
    enableDisable: ['enable', 'disable'],
    elmType: ['input', 'list item', 'checkbox', 'span'],
    enterType: ['verify', 'enter', 'clear field and enter', 'click on'],
    fieldType: [
        'Text Box',
        'Notes Box',
        'Drop-down List',
        'Radio Buttons',
        'Checkboxes',
        'Yes - No',
        'True - False',
        'Signature',
        'File Upload',
        'Slider',
        'Descriptive Text',
        'Begin New Section',
        'Calculated Field',
    ],
    headerOrNot: ['header and', 'header'],
    iframeVisibility: ['', ' in the iframe'],
    inputType: ['input', 'password'],
    instrumentSaveOptions: [
        'Save & Stay',
        'Save & Exit Record',
        'Save & Go To Next Record',
        'Save & Exit Form',
        'Save & Go To Next Form',
        'Save & Go To Next Instance',
        'Save & Add New Instance',
    ],
    labeledElement: labeledElementTypes,
    labeledExactly: ['labeled', 'labeled exactly', 'within the Record Locking Customization table for the Data Collection Instrument named', 'for the Discrepant field labeled', 'within the Record Locking Customization table for the Data Collection Instrument named', 'for the field labeled'],
    loginTypes: ['attempt to login to REDCap with', 'am still logged in to REDCap with', 'login to REDCap with', 'successfully login to REDCap with', 'provide E-Signature credentials for'],
    projectRequestLabel: ['Create Project', 'Send Request'],
    notSeeDC: ['should see a Data Collection Instrument named', 'should NOT see a Data Collection Instrument named', 'should no longer see a Data Collection Instrument named'],
    shouldOrShouldNot: ['should', 'should NOT'],
    storageDirectoryLocations: Object.keys(rctf.STORAGE_DIRECTORY_LOCATIONS),
    ordering: ['ascending', 'descending'],
    onlineDesignerButtons: ['"Enable"', '"Disable"', '"Choose action"', '"Survey settings"', '"Automated Invitations"', 'enabled survey icon', '"View Report"', '"Export Data"', '"Stats & Charts"', '"Execute"', '"Save"'],
    optionalLabeledElement: labeledElementTypes,
    projectStatus: ['Production', 'Development', 'Analysis/Cleanup'],
    projectType: [
        'Practice / Just for fun',
        'Operational Support',
        'Research',
        'Quality Improvement',
        'Other',
    ],
    recordIDEvent: ['record ID', 'event'],
    repeatability: ['enabled', 'disabled', 'modifiable', 'unchangeable'],
    select: ['selected', 'unselected'],
    tableName: ['', ' of the User Rights table', ' of the Reports table', ' of the Participant List table'],
    timeType: ['seconds', 'second', 'minutes', 'minute'],
    toDoRequestTypes: ['Move to prod', 'Approve draft changes', 'Copy project', 'Delete project'],
    toDoTableIcons: [
        'process request',
        'get more information',
        'add or edit a comment',
        'Move to low priority section',
        'archive request notification',
    ],
    toDownloadFile: [' to download a file', ' near "with records in rows" to download a file', ' near "with records in columns" to download a file'],
    userRightAction: ['add', 'remove'],
}